CREATE TABLE CONTACT (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(15) NOT NULL,
    description VARCHAR(30) NOT NULL,
    FK_CLIENT_id INTEGER
);

CREATE TABLE ADDRESS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    ZIP_code VARCHAR(20) NOT NULL DEFAULT '00000-000',
    street VARCHAR(150) NOT NULL DEFAULT '',
    state VARCHAR(100) NOT NULL DEFAULT '',
    neighborhood VARCHAR(100) NOT NULL DEFAULT '',
    country VARCHAR(30) NOT NULL DEFAULT '',
    city VARCHAR(150) NOT NULL DEFAULT ''
);

CREATE TABLE CLIENT (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    active TINYINT(4) NOT NULL DEFAULT 1
    type VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(32) NOT NULL,
    FK_ADDRESS_id INTEGER
);

CREATE TABLE PAINTER (
    id INTEGER AUTO_INCREMENT  PRIMARY KEY,
    dayli_value DOUBLE,
    square_meter_value DECIMAL,
    FK_CLIENT_id INTEGER
);

CREATE TABLE OBJECT (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(20),
    description VARCHAR(255),
    color VARCHAR(10),
    image BLOB,
    square_meter DOUBLE,
    FK_REQUEST_id INTEGER
);

CREATE TABLE MATERIAL (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50),
    value FLOAT,
    FK_REQUEST_id INTEGER
);

CREATE TABLE REQUEST (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    situation VARCHAR(30) NOT NULL DEFAULT 'novo',
    start_date DATETIME NOT NULL DEFAULT now(),
    end_date DATETIME,
    amount FLOAT DEFAULT 0,
    FK_CLIENT_id INTEGER,
    FK_PAINTER_id INTEGER,
    FK_ADDRESS_id INTEGER
);

CREATE TABLE PORTFOLIO (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    description VARCHAR(255),
    FK_PAINTER_id INTEGER
);

CREATE TABLE IMAGE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    image BLOB NOT NULL,
    FK_PORTIFOLIO_id INTEGER
);
 
ALTER TABLE CONTACT ADD CONSTRAINT FK_CONTACT_1
    FOREIGN KEY (FK_CLIENT_id)
    REFERENCES CLIENT (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_1
    FOREIGN KEY (FK_ADDRESS_id)
    REFERENCES ADDRESS (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PAINTER ADD CONSTRAINT FK_PAINTER_1
    FOREIGN KEY (FK_CLIENT_id)
    REFERENCES CLIENT (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_1
    FOREIGN KEY (FK_REQUEST_id)
    REFERENCES REQUEST (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE MATERIAL ADD CONSTRAINT FK_MATERIAL_1
    FOREIGN KEY (FK_REQUEST_id)
    REFERENCES REQUEST (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE REQUEST ADD CONSTRAINT FK_REQUEST_1
    FOREIGN KEY (FK_CLIENT_id)
    REFERENCES CLIENT (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE REQUEST ADD CONSTRAINT FK_REQUEST_2
    FOREIGN KEY (FK_PAINTER_id)
    REFERENCES PAINTER (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE REQUEST ADD CONSTRAINT FK_REQUEST_3
    FOREIGN KEY (FK_ADDRESS_id)
    REFERENCES ADDRESS (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PORTFOLIO ADD CONSTRAINT FK_PORTFOLIO_0
    FOREIGN KEY (FK_PAINTER_id)
    REFERENCES PAINTER (id);
 
ALTER TABLE IMAGE ADD CONSTRAINT FK_IMAGE_1
    FOREIGN KEY (FK_PORTIFOLIO_id)
    REFERENCES PORTFOLIO (id);